version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  activemq:
    image: apache/activemq-classic:latest
    container_name: activemq
    ports:
      - "61616:61616" # ActiveMQ default openwire port
      - "8161:8161"   # ActiveMQ web console
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
    restart: unless-stopped

  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    restart: unless-stopped

volumes:
  mysql_data:
