server:
  servlet:
    context-path: /ecommerce/api/v1
  port: 8081

spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100
  cache:
    type: redis
    redis:
      time-to-live: 600000

cache:
  ttl:
    products: 600000

    categories: 1800000
    carts: 300000
    orders: 900000

jwt:
  secret-key: T3Bwb3J0aW5lVGhpcyBCYXNlNjQgU2VjcmV0IEtleSBGb3IgS0VUMjU2IGtleQ==
  access-token-expiration: 900000
  refresh-token-expiration: 604800000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  health:
    redis:
      enabled: true
    db:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs/swagger.json

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
        type:
          descriptor:
            sql: trace
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
        cache: DEBUG
    net:
      ttddyy:
        dsproxy:
          listener: debug
