server:
  port: 8082
  servlet:
    context-path: /ecommerce
spring:
  application:
    name: category
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1234
    url: jdbc:mysql://localhost:3306/category-db
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update


logging:
  level:
    org:
      springframework:
        security: trace
      zalando:
        logbook: trace


# security
# the value of the jwk set from the authorization server
jwksUri: http://localhost:8081/oauth2/jwks
