INSERT INTO `category` (`name`, `created_at`, `updated_at`) VALUES ('Electronics', NOW(), NOW());
INSERT INTO `category` (`name`, `created_at`, `updated_at`) VALUES ('Smartphones', NOW(), NOW());
INSERT INTO `category` (`name`, `created_at`, `updated_at`) VALUES ('Laptops', NOW(), NOW());
INSERT INTO `category` (`name`, `created_at`, `updated_at`) VALUES ('Tablets', NOW(), NOW());
INSERT INTO `category` (`name`, `created_at`, `updated_at`) VALUES ('Cameras', NOW(), NOW());
INSERT INTO `category` (`name`, `created_at`, `updated_at`) VALUES ('Home Appliances', NOW(), NOW());
INSERT INTO `category` (`name`, `created_at`, `updated_at`) VALUES ('Kitchen Appliances', NOW(), NOW());
INSERT INTO `category` (`name`, `created_at`, `updated_at`) VALUES ('Furniture', NOW(), NOW());
INSERT INTO `category` (`name`, `created_at`, `updated_at`) VALUES ('Office Furniture', NOW(), NOW());
INSERT INTO `category` (`name`, `created_at`, `updated_at`) VALUES ('Clothing', NOW(), NOW());
INSERT INTO `category` (`name`, `created_at`, `updated_at`) VALUES ('Men\'s Fashion', NOW(), NOW());
INSERT INTO `category` (`name`, `created_at`, `updated_at`) VALUES ('Women\'s Fashion', NOW(), NOW());
INSERT INTO `category` (`name`, `created_at`, `updated_at`) VALUES ('Shoes', NOW(), NOW());
INSERT INTO `category` (`name`, `created_at`, `updated_at`) VALUES ('Watches', NOW(), NOW());
INSERT INTO `category` (`name`, `created_at`, `updated_at`) VALUES ('Jewelry', NOW(), NOW());
INSERT INTO `category` (`name`, `created_at`, `updated_at`) VALUES ('Books', NOW(), NOW());
INSERT INTO `category` (`name`, `created_at`, `updated_at`) VALUES ('Stationery', NOW(), NOW());
INSERT INTO `category` (`name`, `created_at`, `updated_at`) VALUES ('Toys', NOW(), NOW());
INSERT INTO `category` (`name`, `created_at`, `updated_at`) VALUES ('Baby Products', NOW(), NOW());
INSERT INTO `category` (`name`, `created_at`, `updated_at`) VALUES ('Beauty & Personal Care', NOW(), NOW());
INSERT INTO `category` (`name`, `created_at`, `updated_at`) VALUES ('Health & Wellness', NOW(), NOW());
INSERT INTO `category` (`name`, `created_at`, `updated_at`) VALUES ('Sports Equipment', NOW(), NOW());
INSERT INTO `category` (`name`, `created_at`, `updated_at`) VALUES ('Fitness Gear', NOW(), NOW());
INSERT INTO `category` (`name`, `created_at`, `updated_at`) VALUES ('Outdoor & Camping', NOW(), NOW());
INSERT INTO `category` (`name`, `created_at`, `updated_at`) VALUES ('Pet Supplies', NOW(), NOW());
INSERT INTO `category` (`name`, `created_at`, `updated_at`) VALUES ('Automotive', NOW(), NOW());
INSERT INTO `category` (`name`, `created_at`, `updated_at`) VALUES ('Motorcycle Accessories', NOW(), NOW());
INSERT INTO `category` (`name`, `created_at`, `updated_at`) VALUES ('Musical Instruments', NOW(), NOW());
INSERT INTO `category` (`name`, `created_at`, `updated_at`) VALUES ('Video Games', NOW(), NOW());
INSERT INTO `category` (`name`, `created_at`, `updated_at`) VALUES ('Home Décor', NOW(), NOW());