server:
  servlet:
    context-path: /ecommerce/api/v1
  port: 9092
spring:
  application.name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/product-service-db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
logging:
  level:
    org:
      zalando:
        logbook: trace
management:
  tracing:
    sampling:
      probability: 1.0  # to help zipkin and micrometer to export logs